### ISSUE TITLE
Github error message when pushing

### ISSUE THREAD

**Issue by jln-** [ossia/score-docs#3]
It seems pushing to the repo causes a Github error message. From what I get this is related to some checking job that fail but no idea exactly what...

It seems harmless as things are properly pushed to the repository and published but maybe worth checking...

**Comment by aklevy** [comment]
So the problem was npm tests which were failing: I added a script npm_test_fix.sh that can be run when the tests are failing, it will try to fix automatically the detected errors and give a detailed report. It should be ok now.
